cacheDurInDays: 10
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=ADMIN_CONFIG_DB;useUnicode=yes;characterEncoding=UTF-8
    username: SA
    password: SAsa@123
  jpa:
    hibernate:
      ddl-auto: none