cacheDurInDays: 10
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=ADMIN_CONFIG_LOOKUP;useUnicode=yes;characterEncoding=UTF-8
    username: SA
    password: SAsa@123
#    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

root:
  admin:
    config:
      code: Root-Admin-Config
      group: Root-Admin-Config-Group
  clearance:
    config:
      code: Root-Clearance-Config
      group: Root-Clearance-Config-Group

devPortal:
  url: http://localhost:8098/users/update-configs
  timeConfig:
    url: http://localhost:8098/users/update-time-configs