cacheDurInDays: 10
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${DB_SERVER};databaseName=${DB_NAME};useUnicode=yes;characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cache:
    type: redis

  redis:
    host: ${REDIS_IP}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

server:
  port: ${SERVER_PORT:8080}

