cacheDurInDays: 10
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${DB_SERVER};databaseName=${DB_NAME};useUnicode=yes;characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  cache:
    type: redis
  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: ${REDIS_IP}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: ${SERVER_PORT:8080}

root:
  admin:
    config:
      code: ${ROOT_ADMIN_CONFIG} # Root-Admin-Config
      group: ${ROOT_ADMIN_CONFIG_GROUP} # Root-Admin-Config-Group
  clearance:
    config:
      code: ${ROOT_CLEARANCE_CONFIG} # Root-Clearance-Config
      group: ${ROOT_CLEARANCE_CONFIG_GROUP} # Root-Clearance-Config-Group

